//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.07 at 05:49:14 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demotivirus.com/Day_032/main/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demotivirus.day_032.main.soap;
