insert into book (title, author) values ('Winter Guest, The', 'Merry Tissier');
insert into book (title, author) values ('King - Jari Litmanen, The (Kuningas Litmanen)', 'Renata Mullord');
insert into book (title, author) values ('Rubber', 'Morton Skayman');
insert into book (title, author) values ('Left Hand of God, The', 'Marabel Szymanek');
insert into book (title, author) values ('Stingray Sam', 'Gerianne Ionn');
insert into book (title, author) values ('Dilemma, The', 'Benetta Le Provest');
insert into book (title, author) values ('Crave', 'Romeo Reary');
insert into book (title, author) values ('I Am Not a Hipster', 'Dannel Shoppee');
insert into book (title, author) values ('Howards End', 'Barbi Angrave');
insert into book (title, author) values ('Gentleman Jim', 'Yuri Sill');
insert into book (title, author) values ('Trouble at Timpetill (Enfants de Timpelbach, Les)', 'Karlee Showte');
insert into book (title, author) values ('Drum, The (Drums)', 'Liana Chesser');
insert into book (title, author) values ('King Lear', 'Leia Randales');
insert into book (title, author) values ('Kissed', 'Guido Claypool');
insert into book (title, author) values ('Radio Flyer', 'Alma Nutbeem');
insert into book (title, author) values ('Souler Opposite, The', 'Gillie Kach');
insert into book (title, author) values ('Me and the Colonel ', 'Rouvin Izakov');
insert into book (title, author) values ('Typhoon (Tae-poong)', 'Slade Gatfield');
insert into book (title, author) values ('Sheriff and the Satellite Kid, The', 'Doe Maccraw');
insert into book (title, author) values ('Collapse', 'Roanna Bridgens');
insert into book (title, author) values ('Living Death', 'Nancie Davie');
insert into book (title, author) values ('Steamboy (Suchîmubôi)', 'Cathleen Bemwell');
insert into book (title, author) values ('Sharon''s Baby', 'Alexine Gierek');
insert into book (title, author) values ('American Adobo', 'Kameko Shorto');
insert into book (title, author) values ('Under the Skin of the City (Zir-e-poost-e Shahr)', 'Marylin Follin');
insert into book (title, author) values ('Mouse on the Moon, The', 'Rodolfo Espino');
insert into book (title, author) values ('Sleuth', 'Oliviero Simyson');
insert into book (title, author) values ('Dragon Inn (Sun lung moon hak chan)', 'Montgomery Abadam');
insert into book (title, author) values ('2 + 2 (Dos más dos)', 'Kort Drewes');
insert into book (title, author) values ('Noriko''s Dinner Table (Noriko no shokutaku)', 'Liliane Mahaddie');
insert into book (title, author) values ('Stingray Sam', 'Marlane Patershall');
insert into book (title, author) values ('It''s the Easter Beagle, Charlie Brown!', 'Rozele Erbain');
insert into book (title, author) values ('Idiot''s Delight', 'Valry Sherston');
insert into book (title, author) values ('King of Ping Pong, The (Ping-pongkingen)', 'Verna Jarad');
insert into book (title, author) values ('Portrait of a Lady, The', 'Stanislas Ravel');
insert into book (title, author) values ('Insanitarium', 'Fairlie Aubury');
insert into book (title, author) values ('It Came from Outer Space', 'Wood Kezor');
insert into book (title, author) values ('Internes Can''t Take Money', 'Doroteya Stuke');
insert into book (title, author) values ('Al Franken: God Spoke', 'Annetta Lowis');
insert into book (title, author) values ('Wives and Lovers', 'Ddene Brisard');
insert into book (title, author) values ('Albert Nobbs', 'Ariel Tapsell');
insert into book (title, author) values ('12 Rounds 2: Reloaded', 'Krishnah Boycott');
insert into book (title, author) values ('Pocket Money', 'Alwin Poel');
insert into book (title, author) values ('One Million Years B.C.', 'Zita Scotland');
insert into book (title, author) values ('Butterfield 8', 'Tricia Brockett');
insert into book (title, author) values ('Giliap', 'Grenville Flecknoe');
insert into book (title, author) values ('Sinivalkoinen valhe', 'Mag Sircomb');
insert into book (title, author) values ('Tender Mercies', 'James Ginman');
insert into book (title, author) values ('Tin Toy', 'Sari Hubert');
insert into book (title, author) values ('Welcome to Australia', 'Raymund Espada');
insert into book (title, author) values ('Tainted', 'Wilhelm Wolland');
insert into book (title, author) values ('Comedy of Terrors, The', 'Towny Clac');
insert into book (title, author) values ('Hero: Love Story of a Spy, The', 'Hobart Belly');
insert into book (title, author) values ('Glass Web, The', 'Terrance Stoffel');
insert into book (title, author) values ('Shadow Puppets', 'Carly De Witt');
insert into book (title, author) values ('Liar, The (Valehtelija)', 'Harriett Carluccio');
insert into book (title, author) values ('30 Years to Life', 'Peria Ramalhete');
insert into book (title, author) values ('Blind Menace, The (Shiranui kengyô)', 'Borden Cridland');
insert into book (title, author) values ('Coast Guard, The (Hae anseon)', 'Lucie Hartford');
insert into book (title, author) values ('Boogeyman', 'Julianne Peacey');
insert into book (title, author) values ('Enemy Mine', 'Nari Brayshaw');
insert into book (title, author) values ('Tai Chi Hero', 'Jonell Krojn');
insert into book (title, author) values ('It''s a Very Merry Muppet Christmas Movie', 'Leanora Goane');
insert into book (title, author) values ('Hunting of the President, The', 'Idaline Richen');
insert into book (title, author) values ('Devil''s Rock, The', 'Petronia Le Pine');
insert into book (title, author) values ('Kingdom of Shadows', 'Janessa Brant');
insert into book (title, author) values ('Shoes of the Fisherman, The', 'Cecilia Dahlman');
insert into book (title, author) values ('Colpo in canna', 'Udell Mackro');
insert into book (title, author) values ('Benchwarmers, The', 'Colan Bellworthy');
insert into book (title, author) values ('Weird Science', 'Vonnie Brok');
insert into book (title, author) values ('Eye of the Tiger', 'Thedric Daly');
insert into book (title, author) values ('Sergeant Körmy and the Underwater Vehicles (Vääpeli Körmy ja vetenalaiset vehkeet)', 'Demetra Friedank');
insert into book (title, author) values ('Sensation of Sight, The', 'Blayne Rowlatt');
insert into book (title, author) values ('Bright Star', 'Isahella Wetheril');
insert into book (title, author) values ('Saints and Soldiers', 'Emily Kinzett');
insert into book (title, author) values ('Air Doll (Kûki ningyô)', 'Corbie Clineck');
insert into book (title, author) values ('Mitchell', 'Vic Fysh');
insert into book (title, author) values ('Rude Awakening', 'Tracey Egdell');
insert into book (title, author) values ('Bread and Roses', 'Hali Matyushenko');
insert into book (title, author) values ('Bridge Too Far, A', 'Vilma Dinjes');
insert into book (title, author) values ('Curse of the Pink Panther', 'Nicolea Salway');
insert into book (title, author) values ('Divine Madness!', 'Devlen Hakes');
insert into book (title, author) values ('Zatoichi and the Chess Expert (Zatôichi Jigoku tabi) (Zatôichi 12)', 'Atlanta Dron');
insert into book (title, author) values ('Accidental Tourist, The', 'Hedvig Farquarson');
insert into book (title, author) values ('Kennedys, The', 'Rosemarie Tedridge');
insert into book (title, author) values ('Just Visiting', 'Ev Swabey');
insert into book (title, author) values ('A Lesson Before Dying', 'Ellissa Swyre');
insert into book (title, author) values ('Eyjafjallajökull', 'Erhart Reinmar');
insert into book (title, author) values ('Nothing''s All Bad', 'Vale Bromont');
insert into book (title, author) values ('Muppet Christmas Carol, The', 'Frederich Rookes');
insert into book (title, author) values ('Ernest & Célestine (Ernest et Célestine)', 'Beau Boud');
insert into book (title, author) values ('Collision Earth', 'Dori Simonato');
insert into book (title, author) values ('I Don''t Want to Be a Man (Ich möchte kein Mann sein)', 'Xaviera Lody');
insert into book (title, author) values ('Mimino', 'Pembroke Tumilty');
insert into book (title, author) values ('Ace Ventura: Pet Detective', 'North Deuss');
insert into book (title, author) values ('It''s Me, It''s Me (Ore Ore)', 'Grace Cruikshank');
insert into book (title, author) values ('You Again', 'Jehanna Augustine');
insert into book (title, author) values ('Atomic Brain, The', 'Albrecht Bellon');
insert into book (title, author) values ('Last Summer', 'Webster Lamputt');
insert into book (title, author) values ('Deathstalker', 'Sherlocke Ellen');
